// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JwtAuthApi.Models;

public partial class UserRole
{
    public int UserID { get; set; }

    public int RoleID { get; set; }

    public virtual Role Role { get; set; }

    public virtual User User { get; set; }
}